import {executionCapability} from '../worker/execution-scope.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {TestD1} from './helpers/d1.mjs';
import {createWorker} from '../worker/index.mjs';
import {D1TaskStore} from '../worker/store.mjs';
const models=[{model:'gpt-5.6-luna',efforts:['low'],isDefault:false}];
const observedModels=()=>({models,observedAt:Date.now(),status:'fresh'});
const children=['codex','claude'].map(provider=>({role:provider,provider,requestedModel:provider==='codex'?'gpt-5.6-luna':'haiku',effort:'low',sufficientReason:'bounded exact arithmetic',acceptanceCriteria:['equals 4'],instructions:'Return 2+2'}));
async function fixture(t){const db=new TestD1();t.after(()=>db.close());let fires=0;const worker=createWorker({fetchFn:async()=>{fires++;return Response.json({claude_code_session_id:'s',claude_code_session_url:'https://claude.ai/code/s'});}}),env={DB:db,ACCESS_TOKEN:'test-secret-01234567890123456789',CLAUDE_ROUTINE_URL:'https://api.anthropic.com/v1/fire',CLAUDE_ROUTINE_TOKEN:'mock'};const post=async(path,input)=>{const r=await worker.fetch(new Request('https://inno.example'+path,{method:'POST',headers:{authorization:'Bearer '+env.ACCESS_TOKEN,'content-type':'application/json'},body:JSON.stringify(input)}),env);return {status:r.status,...await r.json()};};const mcp=async(name,args)=>post('/mcp',{jsonrpc:'2.0',id:1,method:'tools/call',executionCapability:await executionCapability(env.ACCESS_TOKEN,{task:{id:args.taskId},executionId:args.executionId,generation:args.generation}),params:{name,arguments:args}});return {store:new D1TaskStore(db),post,mcp,fires:()=>fires};}
const owner=c=>({executionId:c.executionId,generation:c.generation});
test('HTTP master allocates, preserves siblings, then reviews once with hydrated generated files',async t=>{
 const f=await fixture(t);await f.post('/api/desktop/poll',{models:observedModels()});const {task}=await f.post('/api/tasks',{prompt:'Compare two independent calculations'});await f.post(`/api/tasks/${task.id}/run`,{provider:'codex',expectedVersion:1});const {claim:master}=await f.post('/api/desktop/poll',{});
 const input={...owner(master),content:'Two checkable roles',delegation:{independent:true,children}};
 for(let i=0;i<2;i++)assert.equal((await f.post(`/api/desktop/${task.id}/complete`,input)).status,200);
 assert.equal(f.fires(),1);const parent=await f.store.requireTask(task.id);const claude=await f.store.requireTask(parent.delegation.children.find(c=>c.provider==='claude').taskId);
 const done=await f.mcp('checkpoint_task',{taskId:claude.id,executionId:claude.checkpoint.executionId,generation:claude.checkpoint.generation,content:'4',status:'completed'});assert.equal(done.result.isError,undefined);
 const {claim:child}=await f.post('/api/desktop/poll',{});assert.equal(child.task.parentTaskId,task.id);
 const childResult={...owner(child),content:'4',artifacts:[{name:'answer.txt',mime:'text/plain',encoding:'utf-8',content:'4'}]};
 for(let i=0;i<2;i++)assert.equal((await f.post(`/api/desktop/${child.task.id}/complete`,childResult)).status,200);
 const {claim:review}=await f.post('/api/desktop/poll',{});assert.equal(review.task.id,task.id);assert.equal(review.reviewInputs.length,2);assert.equal(review.reviewInputs.find(c=>c.taskId===child.task.id).artifacts[0].content,'4');
 const report=parent.delegation.children.map(c=>({childTaskId:c.taskId,criteria:[{criterion:'equals 4',status:'pass',evidence:'Recomputed 2+2=4'}]}));
 for(let i=0;i<2;i++)assert.equal((await f.post(`/api/desktop/${task.id}/complete`,{...owner(review),content:'Both equal 4',reviewReport:report})).status,200);
 assert.equal((await f.store.requireTask(task.id)).status,'completed');assert.equal(f.fires(),1);assert.equal((await f.post('/api/desktop/poll',{})).claim,null);
});
test('catalog rejects unsupported assignments before starting either child',async t=>{const f=await fixture(t);const {task}=await f.post('/api/tasks',{prompt:'plan'});const claim=await f.store.claimExecution(task.id,{provider:'claude',expectedVersion:1});const result=await f.mcp('delegate_task',{taskId:task.id,...owner(claim),independent:true,children});assert.equal(result.result.isError,true);assert.equal((await f.store.requireTask(task.id)).status,'running');assert.equal(f.fires(),0);});
async function reviewing(t){const f=await fixture(t);await f.post('/api/desktop/poll',{models:observedModels()});const {task}=await f.post('/api/tasks',{prompt:'independent checks'});await f.post(`/api/tasks/${task.id}/run`,{provider:'codex',expectedVersion:1});const {claim}=await f.post('/api/desktop/poll',{});await f.post(`/api/desktop/${task.id}/complete`,{...owner(claim),content:'planned',delegation:{independent:true,children}});let parent=await f.store.requireTask(task.id);for(const assignment of parent.delegation.children){let child=await f.store.requireTask(assignment.taskId);const c=child.status==='running'?owner(child.checkpoint):owner((await f.post('/api/desktop/poll',{})).claim);await f.post(`/api/desktop/${child.id}/complete`,{...c,content:'4'});}const {claim:review}=await f.post('/api/desktop/poll',{});return {...f,parent,review};}
test('failed review delivery replays without rerunning the successful sibling',async t=>{const f=await reviewing(t);const report=f.parent.delegation.children.map((c,i)=>({childTaskId:c.taskId,criteria:[{criterion:'equals 4',status:i===0?'fail':'pass',evidence:i===0?'wrong formatting':'recomputed 4'}]}));const input={...owner(f.review),content:'Needs correction',reviewReport:report};for(let i=0;i<2;i++)assert.equal((await f.post(`/api/desktop/${f.parent.id}/complete`,input)).status,200);const parent=await f.store.requireTask(f.parent.id);assert.equal(parent.delegation.retryCount,1);assert.equal((await f.store.requireTask(parent.delegation.children[1].taskId)).status,'completed');assert.equal(f.fires(),1);});
test('unverifiable review persists evidence and replay returns the same decision',async t=>{const f=await reviewing(t);const report=f.parent.delegation.children.map(c=>({childTaskId:c.taskId,criteria:[{criterion:'equals 4',status:'unverifiable',evidence:'Independent source missing'}]}));const input={...owner(f.review),content:'Cannot verify',reviewReport:report};const first=await f.post(`/api/desktop/${f.parent.id}/complete`,input);assert.equal(first.status,200);assert.equal(first.task.status,'waiting_user');assert.deepEqual(first.task.delegation.reviewReport,report);const second=await f.post(`/api/desktop/${f.parent.id}/complete`,input);assert.equal(second.status,200);assert.equal(second.task.version,first.task.version);});
test('HTTP recovery requires explicit stopped confirmation and retains completed child',async t=>{const f=await fixture(t);await f.post('/api/desktop/poll',{models:observedModels()});const parent=await f.store.createTask({prompt:'checks'}),master=await f.store.claimExecution(parent.id,{provider:'codex',expectedVersion:1});const allocated=await f.post(`/api/desktop/${parent.id}/complete`,{...owner(master),content:'plan',delegation:{independent:true,children}});const claude=await f.store.requireTask(allocated.task.delegation.children[1].taskId);await f.store.markExecutionUncertain(claude.id,{...owner(claude.checkpoint),reason:'uncertain_fire'});let p=await f.store.requireTask(parent.id),c=await f.store.requireTask(claude.id);const input={expectedVersion:p.version,childTaskId:c.id,expectedChildVersion:c.version};assert.equal((await f.post(`/api/tasks/${p.id}/delegation/recover`,input)).status,400);assert.equal((await f.post(`/api/tasks/${p.id}/delegation/recover`,{...input,confirmedStopped:true})).status,200);assert.equal(f.fires(),2);});
test('legacy desktop model arrays cannot authorize HTTP delegation',async t=>{
 const f=await fixture(t);assert.equal((await f.post('/api/desktop/poll',{models})).status,200);
 const {task}=await f.post('/api/tasks',{prompt:'legacy desktop check'});
 const claim=await f.store.claimExecution(task.id,{provider:'codex',expectedVersion:1});
 const denied=await f.post(`/api/desktop/${task.id}/complete`,{...owner(claim),content:'plan',delegation:{independent:true,children}});
 assert.equal(denied.status,400);assert.match(JSON.stringify(denied),/Reconnect desktop.*Codex model/i);
 assert.equal((await f.store.requireTask(task.id)).status,'running');assert.equal(f.fires(),0);
});
