import test from 'node:test';
import assert from 'node:assert/strict';
import {createTask} from '../public/core/tasks.mjs';
import {allocateDelegation,validateAssignments} from '../public/core/delegation.mjs';
import {D1TaskStore} from '../worker/store.mjs';
import {Delegations} from '../worker/delegations.mjs';
import {TestD1} from './helpers/d1.mjs';
const assignments=()=>['codex','claude'].map((provider,i)=>({role:'role-'+i,provider,requestedModel:provider==='codex'?'test-model':'sonnet',effort:'high',sufficientReason:'sufficient',acceptanceCriteria:['verify source'],instructions:'Use assigned evidence',sourceIds:[i?'b':'a']}));
function fixture(){const parent=createTask({prompt:'Analyze two connected sources',attachments:[{id:'a',name:'a.txt',size:100,source:'file',view:{kind:'text-byte-range',start:0,end:5,sha256:'a'.repeat(64)}},{id:'b',name:'b.txt',source:'file'}]});parent.status='running';parent.checkpoint={provider:'codex',executionId:'owner',generation:1,sourceBound:true};return {parent,input:{executionId:'owner',generation:1,independent:true,children:assignments()}};}
const gate={sourceDelegationVersion:1};
test('source assignment is disabled by default and cannot be enabled by request payload',()=>{const {parent,input}=fixture();assert.throws(()=>validateAssignments(parent,{...input,...gate}),/source/i);});
test('enabled allocation copies only chosen metadata and preserves selected coverage',()=>{const {parent,input}=fixture();parent.attachments[0].content='PRIVATE_ORIGINAL';parent.attachments[0].data='PRIVATE_BYTES';let seq=0;const allocation=allocateDelegation(parent,input,{...gate,now:()=>new Date().toISOString(),id:()=>`new-${++seq}`});assert.deepEqual(allocation.children.map(c=>c.attachments.map(a=>a.id)),[['a'],['b']]);assert.equal(allocation.children[0].attachments[0].view.sha256,'a'.repeat(64));assert.deepEqual(allocation.children[0].assignment.sourceIds,['a']);assert.equal(JSON.stringify(allocation.children).includes('PRIVATE'),false);assert.equal(parent.status,'running');});
test('enabled source selection rejects unknown duplicate URL and injected materials',()=>{for(const change of [i=>i.children[0].sourceIds=['missing'],i=>i.children[0].sourceIds=['a','a'],i=>i.children[0].sourceIds='a',i=>i.children[0].materials=[{text:'private'}]]){const {parent,input}=fixture();change(input);assert.throws(()=>validateAssignments(parent,input,gate));}const {parent,input}=fixture();parent.attachments[0]={id:'a',name:'url',source:'url',url:'https://example.test'};assert.throws(()=>validateAssignments(parent,input,gate),/URL/);});
test('D1 gated allocation persists selected scopes atomically and replay does not create new children',async t=>{const db=new TestD1();t.after(()=>db.close());const store=new D1TaskStore(db);const {parent:template}=fixture();const parent=await store.createTask({prompt:template.prompt,attachments:template.attachments});const owner=await store.claimExecution(parent.id,{provider:'codex',expectedVersion:parent.version,sourceBound:true});const service=new Delegations(store,gate),input={executionId:owner.executionId,generation:owner.generation,independent:true,children:assignments()};const first=await service.allocate(parent.id,input);assert.deepEqual(first.children.map(c=>c.attachments.map(a=>a.id)),[['a'],['b']]);const replay=await service.allocate(parent.id,input);assert.equal(replay.replayed,true);assert.equal((await store.listTasks()).length,3);assert.deepEqual(replay.children.map(c=>c.id),first.children.map(c=>c.id));});

import {handleMcp} from '../server/mcp.mjs';
import {validateDelegationResult} from '../server/model-routing.mjs';
test('source IDs remain gated through model-result parsing and advertised MCP schema',async()=>{const rows=[{model:'test-model',efforts:['high']}],input={independent:true,children:assignments()};assert.throws(()=>validateDelegationResult(input,rows),/source/i);assert.deepEqual(validateDelegationResult(input,rows,gate).children[0].sourceIds,['a']);for(const enabled of [false,true]){const message=await handleMcp({}, {jsonrpc:'2.0',id:1,method:'tools/list'}, {delegate:()=>{},...(enabled?gate:{})});const tool=message.result.tools.find(t=>t.name==='delegate_task');assert.equal(Boolean(tool.inputSchema.properties.children.items.properties.sourceIds),enabled);}});
test('source selection rejects ambiguous paths and unreferenced transient originals even when enabled',()=>{const {parent,input}=fixture();parent.attachments[1].path=parent.attachments[0].path;assert.throws(()=>validateAssignments(parent,input,gate),/distinct/);parent.attachments=[];assert.throws(()=>validateAssignments(parent,input,gate),/Source-bound/);});
test('a failed atomic source allocation cannot leave a child or parent transition',async t=>{const db=new TestD1();t.after(()=>db.close());const store=new D1TaskStore(db),{parent:template}=fixture();const parent=await store.createTask({prompt:template.prompt,attachments:template.attachments});const owner=await store.claimExecution(parent.id,{provider:'codex',expectedVersion:1,sourceBound:true});const original=db.batch.bind(db);db.batch=statements=>original([...statements.slice(0,2),db.prepare('INSERT INTO nonexistent_table VALUES (1)'),...statements.slice(2)]);await assert.rejects(()=>new Delegations(store,gate).allocate(parent.id,{executionId:owner.executionId,generation:owner.generation,independent:true,children:assignments()}));assert.equal((await store.requireTask(parent.id)).status,'running');assert.equal((await store.listTasks()).length,1);});

import {delegationRoutingPolicy} from '../server/model-routing.mjs';
test('source-capable planner describes scoped IDs without the contradictory source-free requirement',()=>{const rows=[{model:'test-model',efforts:['high']}];assert.match(delegationRoutingPolicy(rows),/attachment-backed/);const policy=delegationRoutingPolicy(rows,gate);assert.match(policy,/sourceIds/);assert.doesNotMatch(policy,/attachment-backed|source-free results|without source originals or dependencies/);assert.match(policy,/original text/i);});

import {sourceDelegationContext} from '../public/core/delegation-sources.mjs';
test('planner source references contain metadata only and unsupported references stay direct',()=>{const {parent}=fixture();parent.attachments[0].text='PRIVATE_SOURCE';assert.equal(sourceDelegationContext(parent), '');const context=sourceDelegationContext(parent,gate);assert.match(context,/sourceIds/);assert.equal(context.includes('PRIVATE_SOURCE'),false);parent.attachments[0].source='url';parent.attachments[0].url='https://example.test';assert.equal(sourceDelegationContext(parent,gate),'');});
