import test from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'node:fs';
import path from 'node:path';
import {request as httpRequest} from 'node:http';
import {createHash} from 'node:crypto';
import {createDesktopBridge} from '../server/desktop-bridge.mjs';
import {createDesktopServer} from '../server/desktop-http.mjs';
import {createFileOutbox} from '../server/file-outbox.mjs';
import {createOutboxRecovery} from '../server/outbox-recovery.mjs';
import {createDeliveryReceipt} from '../public/core/delivery-receipt.mjs';
const token='local-drain-test-01234567890123456789',binding={origin:'https://inno.example',workspaceId:'11111111-1111-4111-8111-111111111111'};
const pending=()=>({version:1,phase:'pending',binding,taskId:'task',action:'complete',input:{executionId:'exec',generation:1,content:'PRIVATE_SAVED_PAYLOAD'}});
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
async function receipt(input=pending().input){return {...await createDeliveryReceipt({workspaceId:binding.workspaceId,taskId:'task',action:'complete',input}),acceptedAt:'2026-10-01T00:00:00.000Z'};}
async function fixture(t,{version=1,hook=()=>{},helperHook=helper=>helper}={}){
 const root=path.resolve('.inno/tmp');fs.mkdirSync(root,{recursive:true});const dir=fs.mkdtempSync(path.join(root,'drain-')),file=path.join(dir,'pending.json'),outbox=createFileOutbox(file);outbox.write(pending());const calls=[];let outboxReads=0;
 outbox.read=()=>{outboxReads++;assert.fail('unbounded outbox read');};
 const bridge=createDesktopBridge({deliveryReceiptVersion:version,outbox,readDeliveryBinding:async()=>binding,beforeClaim:()=>assert.fail('claim preparation'),runner:{models:()=>assert.fail(),run:()=>assert.fail('AI')},request:async(route,input,options)=>{calls.push({route,input,options});await hook(route,input);if(route.endsWith('/complete'))return {deliveryReceipt:await receipt(input)};if(route.endsWith('/ack'))return {receipt:input.receipt,released:true};assert.fail('new claim');}});
 const helper=helperHook(createOutboxRecovery(file,{withExclusive:work=>bridge.recoveryMaintenance(work)}));
 const server=createDesktopServer({token,publicDir:new URL('../public',import.meta.url),bridge,request:()=>assert.fail('cloud proxy'),deliveryReceiptVersion:version,outboxRecovery:helper});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 t.after(async()=>{bridge.stop();await bridge.settled();await new Promise(r=>server.close(r));for(const name of [file,file+'.tmp'])if(fs.existsSync(name))fs.unlinkSync(name);fs.rmdirSync(dir);});
 const call=(input,options={})=>new Promise((resolve,reject)=>{const req=httpRequest({hostname:'127.0.0.1',port:server.address().port,path:options.route??'/api/desktop/recovery/drain',method:options.method??'POST',headers:{connection:'close','content-type':'application/json',...(options.auth===false?{}:{authorization:'Bearer '+token}),...(options.origin?{origin:options.origin}:{}),...(options.host?{host:options.host}:{})}},res=>{let raw='';res.setEncoding('utf8');res.on('data',chunk=>raw+=chunk);res.on('end',()=>resolve({status:res.statusCode,body:JSON.parse(raw)}));});req.on('error',reject);req.end(input===undefined?undefined:JSON.stringify(input));});
 const preview=async()=>{const result=await call(undefined,{route:'/api/desktop/recovery',method:'GET'});assert.equal(result.status,200);return result.body.recovery.pending.sha256;};
 return {file,outbox,bridge,helper,calls,call,preview,reads:()=>outboxReads};
}
test('HTTP preview hash drains captured pending then ACK with no unbounded read or postcommit status',async t=>{const f=await fixture(t),pendingHash=await f.preview();f.bridge.runtimeStatus=()=>assert.fail('postcommit status');assert.deepEqual(await f.call({pendingHash,confirm:true}),{status:200,body:{drained:true}});assert.deepEqual(f.calls.map(c=>c.route),['/api/desktop/task/complete','/api/desktop/task/ack']);assert.equal(fs.existsSync(f.file),false);assert.equal(f.reads(),0);assert.equal(await f.bridge.tick(),false);await assert.rejects(()=>f.bridge.startTask('task',{materials:[]}));});
test('ACK pending drains only ACK and never returns receipt or payload',async t=>{const f=await fixture(t);fs.writeFileSync(f.file,JSON.stringify({version:1,phase:'ack_pending',binding,receipt:await receipt()}));const result=await f.call({pendingHash:await f.preview(),confirm:true});assert.deepEqual(result,{status:200,body:{drained:true}});assert.deepEqual(f.calls.map(c=>c.route),['/api/desktop/task/ack']);assert.equal(f.reads(),0);});
test('wrong hash, changed preview, missing, legacy, invalid, oversize and tmp preserve files without requests',async t=>{for(const kind of ['hash','changed','missing','legacy','invalid','oversize','tmp']){const f=await fixture(t);let pendingHash=await f.preview();if(kind==='hash')pendingHash='0'.repeat(64);if(kind==='changed')fs.writeFileSync(f.file,JSON.stringify({...pending(),input:{...pending().input,content:'different'}}));if(kind==='missing')fs.unlinkSync(f.file);if(kind==='legacy'){const {version,phase,...legacy}=pending();fs.writeFileSync(f.file,JSON.stringify(legacy));pendingHash=hash(fs.readFileSync(f.file));}if(kind==='invalid'){fs.writeFileSync(f.file,'PRIVATE_INVALID');pendingHash=hash(fs.readFileSync(f.file));}if(kind==='oversize'){fs.writeFileSync(f.file,Buffer.alloc(1024*1024+1));pendingHash=hash(fs.readFileSync(f.file));}if(kind==='tmp')fs.writeFileSync(f.file+'.tmp',JSON.stringify(pending()));const before=fs.existsSync(f.file)?fs.readFileSync(f.file):null,tmp=fs.existsSync(f.file+'.tmp')?fs.readFileSync(f.file+'.tmp'):null;const result=await f.call({pendingHash,confirm:true});assert.equal(result.status,409,kind);assert.equal(JSON.stringify(result).includes('PRIVATE'),false);assert.deepEqual(fs.existsSync(f.file)?fs.readFileSync(f.file):null,before);assert.deepEqual(fs.existsSync(f.file+'.tmp')?fs.readFileSync(f.file+'.tmp'):null,tmp);assert.equal(f.calls.length,0);assert.equal(f.reads(),0);}});
test('strict confirmation and input fields reject before helper callback',async t=>{let reads=0;const f=await fixture(t,{helperHook:h=>({...h,readPending:async()=>{reads++;throw Error('PRIVATE');}})}),pendingHash=hash(fs.readFileSync(f.file));for(const input of [null,[],{}, {pendingHash,confirm:false},{pendingHash,confirm:true,path:f.file},{pendingHash:null,confirm:true},{pendingHash:pendingHash.toUpperCase(),confirm:true},{pendingHash:0,confirm:true}]){const response=await f.call(input);assert.equal(response.status,409);assert.equal(JSON.stringify(response).includes('PRIVATE'),false);}assert.equal(reads,0);assert.equal(f.calls.length,0);});
test('gate and auth apply to drain while old helpers keep inspect available and separate capability',async t=>{for(const config of [{version:0},{helperHook:h=>({inspect:h.inspect,promote:h.promote})}]){const f=await fixture(t,config);assert.equal((await f.call({pendingHash:hash(fs.readFileSync(f.file)),confirm:true})).status,404);const status=await f.call(undefined,{route:'/api/desktop/status',method:'GET'});assert.equal(status.body.capabilities.desktopOutboxDrain,false);assert.equal(status.body.capabilities.desktopOutboxRecovery,!!config.helperHook);assert.equal(f.calls.length,0);if(config.helperHook)assert.equal((await f.call(undefined,{route:'/api/desktop/recovery',method:'GET'})).status,200);}const f=await fixture(t);assert.equal((await f.call(undefined,{route:'/api/desktop/status',method:'GET'})).body.capabilities.desktopOutboxDrain,true);for(const options of [{auth:false},{origin:'https://evil.example'},{host:'evil.example'}])assert.equal((await f.call({pendingHash:await f.preview(),confirm:true},options)).status,options.auth===false?401:403);assert.equal(f.calls.length,0);});
test('busy and stopped drains preserve bytes without reading or delivering',async t=>{for(const mode of ['busy','stopped']){const f=await fixture(t),bytes=fs.readFileSync(f.file),gate=deferred();let work;if(mode==='busy')work=f.bridge.recoveryInspect(()=>gate.promise);else f.bridge.stop();try{assert.equal((await f.call({pendingHash:hash(bytes),confirm:true})).status,409);assert.deepEqual(fs.readFileSync(f.file),bytes);assert.equal(f.calls.length,0);}finally{gate.resolve();if(work)await work;}}});
test('concurrent HTTP drains admit one and hold recovery lock through delivery',async t=>{const entered=deferred(),gate=deferred(),f=await fixture(t,{hook:async route=>{if(route.endsWith('/complete')){entered.resolve();await gate.promise;}}}),input={pendingHash:await f.preview(),confirm:true};const first=f.call(input);try{await entered.promise;assert.equal((await f.call(input)).status,409);}finally{gate.resolve();}assert.equal((await first).status,200);assert.equal(f.calls.length,2);assert.equal(f.bridge.runtimeStatus().recoveryPaused,true);});
test('stop during trusted async read prevents even identity lookup and settled waits for read',async()=>{const gate=deferred(),entered=deferred();let reads=0;const bridge=createDesktopBridge({deliveryReceiptVersion:1,outbox:{read:()=>assert.fail()},readDeliveryBinding:()=>assert.fail('identity'),request:()=>assert.fail('request'),runner:{run:()=>assert.fail()}});const work=bridge.drainPending({readPending:async()=>{reads++;entered.resolve();await gate.promise;return pending();}});const checked=assert.rejects(()=>work);await entered.promise;bridge.stop();let settled=false;const settling=bridge.settled().then(()=>settled=true);await new Promise(r=>setImmediate(r));assert.equal(settled,false);gate.resolve();await checked;await settling;assert.equal(reads,1);assert.equal(bridge.runtimeStatus().recoveryPaused,true);});
test('ACK reply loss preserves ack_pending; stale preview refuses and fresh retry sends ACK only',async t=>{let fail=true;const f=await fixture(t,{hook:route=>{if(fail&&route.endsWith('/ack'))throw Error('PRIVATE_ACK_LOSS');}}),original=await f.preview();const lost=await f.call({pendingHash:original,confirm:true});assert.equal(lost.status,500);assert.equal(JSON.stringify(lost).includes('PRIVATE'),false);assert.equal(JSON.parse(fs.readFileSync(f.file)).phase,'ack_pending');assert.equal((await f.call({pendingHash:original,confirm:true})).status,409);fail=false;assert.equal((await f.call({pendingHash:await f.preview(),confirm:true})).status,200);assert.deepEqual(f.calls.map(c=>c.route),['/api/desktop/task/complete','/api/desktop/task/ack','/api/desktop/task/ack']);assert.equal(f.reads(),0);});
test('helper returns validated captured record only internally and rejects invalid hash',async t=>{const f=await fixture(t);await assert.rejects(()=>f.helper.readPending(null),{status:409});const expected=hash(fs.readFileSync(f.file));assert.deepEqual(await f.bridge.recoveryInspect(()=>f.helper.readPending(expected)),pending());assert.equal(f.calls.length,0);});
test('missing bridge drain method disables only drain capability and route',async t=>{const f=await fixture(t);f.bridge.drainPending=undefined;
 // Gate is captured when the server is constructed, so use a separate local server.
 const server=createDesktopServer({token,publicDir:new URL('../public',import.meta.url),bridge:f.bridge,request:()=>assert.fail(),deliveryReceiptVersion:1,outboxRecovery:f.helper});await new Promise(r=>server.listen(0,'127.0.0.1',r));try{const get=route=>new Promise((resolve,reject)=>{const req=httpRequest({hostname:'127.0.0.1',port:server.address().port,path:route,headers:{connection:'close',authorization:'Bearer '+token}},res=>{let raw='';res.on('data',c=>raw+=c);res.on('end',()=>resolve(JSON.parse(raw)));});req.on('error',reject);req.end();});assert.deepEqual((await get('/api/desktop/status')).capabilities,{desktopOutboxRecovery:true,desktopOutboxDrain:false,desktopLegacyRecovery:true});}finally{await new Promise(r=>server.close(r));}assert.equal(f.calls.length,0);});
test('unsupported drain methods and lookalike paths never reach helper or cloud',async t=>{const f=await fixture(t),input={pendingHash:await f.preview(),confirm:true};for(const options of [{method:'GET'},{method:'PUT'},{route:'/api/desktop/recovery/drain/extra'},{route:'/api/desktop/recovery/drain-more'}])assert.equal((await f.call(options.method==='GET'?undefined:input,options)).status,404);assert.equal(f.calls.length,0);assert.equal(f.bridge.runtimeStatus().recoveryPaused,false);});
test('result response loss preserves exact pending hash and permits explicit replay without claim',async t=>{let lost=true;const f=await fixture(t,{hook:route=>{if(lost&&route.endsWith('/complete'))throw Error('PRIVATE_RESULT_LOSS');}}),pendingHash=await f.preview(),before=fs.readFileSync(f.file);assert.equal((await f.call({pendingHash,confirm:true})).status,500);assert.deepEqual(fs.readFileSync(f.file),before);lost=false;assert.deepEqual(await f.call({pendingHash,confirm:true}),{status:200,body:{drained:true}});assert.deepEqual(f.calls.map(c=>c.route),['/api/desktop/task/complete','/api/desktop/task/complete','/api/desktop/task/ack']);assert.equal(f.reads(),0);assert.equal(await f.bridge.tick(),false);});
test('bounded helper never admits BOM or invalid UTF8 and reads at most limit plus one',async t=>{const f=await fixture(t);for(const bytes of [Buffer.concat([Buffer.from([239,187,191]),Buffer.from(JSON.stringify(pending()))]),Buffer.from([255,254])]){fs.writeFileSync(f.file,bytes);await assert.rejects(()=>f.helper.readPending(hash(bytes)),{status:409});assert.deepEqual(fs.readFileSync(f.file),bytes);}fs.writeFileSync(f.file,Buffer.alloc(2*1024*1024));let readBytes=0,opens=0;const bounded=createOutboxRecovery(f.file,{fs:{...fs,openSync:(...args)=>{opens++;return fs.openSync(...args);},readSync:(...args)=>{const count=fs.readSync(...args);readBytes+=count;return count;}}});await assert.rejects(()=>bounded.readPending('0'.repeat(64)),{status:409});assert.equal(opens,1);assert.equal(readBytes,1024*1024+1);assert.equal(f.calls.length,0);});
