import test from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'node:fs';
import path from 'node:path';
import {request as httpRequest} from 'node:http';
import {createDesktopBridge} from '../server/desktop-bridge.mjs';
import {createDesktopServer} from '../server/desktop-http.mjs';
import {createFileOutbox} from '../server/file-outbox.mjs';
import {createOutboxRecovery} from '../server/outbox-recovery.mjs';
import {runDesktopService} from '../server/desktop-service.mjs';
import {acquireBridgeLock} from '../server/bridge-runtime.mjs';
import {createDeliveryReceipt} from '../public/core/delivery-receipt.mjs';
const binding={origin:'https://inno.example',workspaceId:'11111111-1111-4111-8111-111111111111'};
const pending={version:1,phase:'pending',binding,taskId:'task',action:'complete',input:{executionId:'exec',generation:1,content:'saved'}};
function fixture(t){const root=path.resolve('.inno/tmp');fs.mkdirSync(root,{recursive:true});const dir=fs.mkdtempSync(path.join(root,'service-')),file=path.join(dir,'pending.json');t.after(()=>{for(const name of [file,file+'.tmp'])if(fs.existsSync(name))fs.unlinkSync(name);fs.rmdirSync(dir);});return {file,outbox:createFileOutbox(file)};}
const turn=()=>new Promise(r=>setImmediate(r));
test('real saved drain stays paused, sends result/ACK only and tracks settled until completion',async t=>{const f=fixture(t);f.outbox.write(pending);const calls=[];let release,entered;const gate=new Promise(r=>release=r),ready=new Promise(r=>entered=r);const bridge=createDesktopBridge({deliveryReceiptVersion:1,outbox:f.outbox,readDeliveryBinding:async()=>binding,beforeClaim:()=>assert.fail('claim preparation'),runner:{models:()=>assert.fail(),run:()=>assert.fail()},request:async(route,input)=>{calls.push(route);if(route.endsWith('/complete')){entered();await gate;return {deliveryReceipt:{...await createDeliveryReceipt({workspaceId:binding.workspaceId,taskId:'task',action:'complete',input}),acceptedAt:'2026-10-01T00:00:00.000Z'}};}return {receipt:input.receipt,released:true};}});const draining=bridge.drainPending();await ready;let settled=false;const settling=bridge.settled().then(()=>settled=true);await turn();assert.equal(settled,false);await assert.rejects(()=>bridge.drainPending());release();assert.equal(await draining,true);await settling;assert.equal(f.outbox.read(),null);assert.equal(bridge.runtimeStatus().recoveryPaused,true);assert.equal(await bridge.tick(),false);assert.equal(await bridge.drainPending(),false);assert.deepEqual(calls,['/api/desktop/task/complete','/api/desktop/task/ack']);});
test('drain failure keeps saved file and pause; stopped drain is forbidden',async t=>{const f=fixture(t);f.outbox.write(pending);const bridge=createDesktopBridge({deliveryReceiptVersion:1,outbox:f.outbox,readDeliveryBinding:async()=>binding,runner:{run:()=>assert.fail()},request:async()=>{throw Error('lost');}});await assert.rejects(()=>bridge.drainPending(),/lost/);await bridge.settled();assert.deepEqual(f.outbox.read(),pending);assert.equal(bridge.runtimeStatus().busy,false);assert.equal(bridge.runtimeStatus().recoveryPaused,true);bridge.stop();await assert.rejects(()=>bridge.drainPending());});
test('park retains real HTTP and process lock, recovery promotion cannot restart AI, shutdown closes in order',async t=>{const f=fixture(t);fs.writeFileSync(f.file+'.tmp',JSON.stringify(pending));let cloud=0;const bridge=createDesktopBridge({deliveryReceiptVersion:1,outbox:f.outbox,readDeliveryBinding:async()=>binding,runner:{run:()=>assert.fail()},request:async()=>{cloud++;assert.fail();}});const helper=createOutboxRecovery(f.file,{withExclusive:work=>bridge.recoveryMaintenance(work)}),lock=await acquireBridgeLock(0),controller=new AbortController(),events=[];const server=createDesktopServer({token:'test-token-01234567890123456789',publicDir:new URL('../public',import.meta.url),bridge,request:()=>assert.fail(),deliveryReceiptVersion:1,outboxRecovery:helper});await new Promise(r=>server.listen(0,'127.0.0.1',r));let closed=false;t.after(async()=>{controller.abort();bridge.stop();if(!closed){await new Promise(r=>server.close(r));await lock.close();}});const service=runDesktopService({bridge,deliveryReceiptVersion:1,signal:controller.signal,wait:()=>assert.fail('park timer')});await turn();assert.equal(bridge.runtimeStatus().recoveryPaused,true);const status=await new Promise((resolve,reject)=>{const req=httpRequest({hostname:'127.0.0.1',port:server.address().port,path:'/api/desktop/status',headers:{authorization:'Bearer test-token-01234567890123456789',connection:'close'}},res=>{res.resume();res.on('end',()=>resolve(res.statusCode));});req.on('error',reject);req.end();});assert.equal(status,200);await assert.rejects(()=>acquireBridgeLock(lock.port),{code:'EADDRINUSE'});const snapshot=await bridge.recoveryInspect(()=>helper.inspect());assert.equal((await helper.promote({pendingHash:null,temporaryHash:snapshot.temporary.sha256,confirm:true})).promoted,true);await turn();assert.equal(cloud,0);assert.equal(await bridge.tick(),false);controller.abort();bridge.stop();await service;events.push('service');await bridge.settled();events.push('settled');await new Promise(r=>server.close(r));events.push('http');await lock.close();events.push('lock');closed=true;assert.deepEqual(events,['service','settled','http','lock']);const reacquired=await acquireBridgeLock(lock.port);await reacquired.close();});
