import test from 'node:test';
import assert from 'node:assert/strict';
import {D1TaskStore} from '../worker/store.mjs';
import {TestD1} from './helpers/d1.mjs';
import {CloudBridge} from '../worker/bridge.mjs';
import {dispatchClaude} from '../worker/dispatch.mjs';
async function queued(store,{provider='codex',sources=true,status='queued'}={}){let task=await store.createTask({prompt:'independent work',attachments:sources?[{id:'source',name:'evidence.txt',source:'file'}]:[]});return store.replaceTask(task.id,task.version,t=>({...t,status,version:t.version+1,updatedAt:store.now(),checkpoint:{provider,status},...(status==='queued_for_review'?{delegation:{state:status,masterProvider:provider}}:{})}));}
for(const status of ['queued','queued_for_review'])test(`automatic Claude dispatch preserves ${status} source work without firing`,async t=>{const db=new TestD1();t.after(()=>db.close());const store=new D1TaskStore(db),task=await queued(store,{provider:'claude',status});let fires=0;const result=await dispatchClaude({store,taskId:task.id,hasRoutine:true,fire:async()=>{fires++;return {claude_code_session_url:'https://claude.ai/code/test'};}});assert.equal(fires,0);assert.deepEqual(result,task);assert.deepEqual(await store.requireTask(task.id),task);});
for(const status of ['queued','queued_for_review'])test(`desktop queue skips ${status} source work without starving independent jobs`,async t=>{const db=new TestD1();t.after(()=>db.close());let time=0;const store=new D1TaskStore(db,{now:()=>new Date(1700000000000+time++*1000).toISOString()}),blocked=await queued(store,{status}),ready=await queued(store,{sources:false});const bridge=new CloudBridge(store),claim=await bridge.claim();assert.equal(claim?.task.id,ready.id);assert.deepEqual(await store.requireTask(blocked.id),blocked);assert.equal(await bridge.claim(),null);});

import {Delegations} from '../worker/delegations.mjs';
const sourceAssignments=['codex','claude'].map(provider=>({provider,role:provider,requestedModel:provider==='codex'?'test-model':'sonnet',effort:'high',sufficientReason:'source analysis',acceptanceCriteria:['verified'],instructions:'Read selected evidence',sourceIds:['source']}));
async function sourceBatch(store){let parent=await store.createTask({prompt:'source analysis',attachments:[{id:'source',name:'evidence.txt',source:'file'}]});const owner=await store.claimExecution(parent.id,{provider:'codex',expectedVersion:parent.version,sourceBound:true});const service=new Delegations(store,{sourceDelegationVersion:1});return {...await service.allocate(parent.id,{executionId:owner.executionId,generation:owner.generation,independent:true,children:sourceAssignments}),service};}
test('gated desktop source child and review start preserve ownership and hydrate queue phase',async t=>{const db=new TestD1();t.after(()=>db.close());const store=new D1TaskStore(db),batch=await sourceBatch(store),bridge=new CloudBridge(store,{sourceDelegationVersion:1});const child=batch.children[0];await assert.rejects(()=>bridge.start(child.id,{expectedVersion:child.version,sourceDelegationVersion:1,sourceNames:[]}),/Reconnect/);assert.equal((await store.requireTask(child.id)).status,'queued');const first=await bridge.start(child.id,{expectedVersion:child.version,sourceDelegationVersion:1,sourceNames:['evidence.txt']});assert.equal(first.task.checkpoint.sourceBound,true);await assert.rejects(()=>bridge.start(child.id,{expectedVersion:child.version,sourceDelegationVersion:1,sourceNames:['evidence.txt']}));await store.finishExecution(child.id,{...first,content:'verified evidence'});const other=batch.children[1],claim=await store.claimExecution(other.id,{provider:'claude',expectedVersion:other.version,sourceBound:true});await store.finishExecution(other.id,{...claim,content:'verified evidence'});const review=await batch.service.reconcile(batch.parent.id);assert.equal(review.parent.status,'queued_for_review');assert.equal(await bridge.claim(),null);const owner=await bridge.start(review.parent.id,{expectedVersion:review.parent.version,sourceDelegationVersion:1,sourceNames:['evidence.txt']});assert.equal(owner.task.delegation.state,'reviewing');assert.equal(owner.task.checkpoint.sourceBound,true);});

import {createWorker} from '../worker/index.mjs';
test('direct Claude child validates sources before fire and keeps excerpts out of stored state',async t=>{
 const db=new TestD1();t.after(()=>db.close());const store=new D1TaskStore(db),batch=await sourceBatch(store),child=batch.children[1];let fires=0,prompt='';const env={DB:db,ACCESS_TOKEN:'test-secret-01234567890123456789',CLAUDE_ROUTINE_URL:'https://api.anthropic.com/v1/fire',CLAUDE_ROUTINE_TOKEN:'mock'};
 const fetchFn=async(url,options)=>{fires++;prompt=JSON.parse(options.body).text;return Response.json({claude_code_session_id:'s',claude_code_session_url:'https://claude.ai/code/s'});};const worker=createWorker({fetchFn,sourceDelegationVersion:1});const post=(app,materials)=>app.fetch(new Request('https://inno.test/api/tasks/'+child.id+'/run',{method:'POST',headers:{authorization:'Bearer '+env.ACCESS_TOKEN,'content-type':'application/json'},body:JSON.stringify({provider:'claude',expectedVersion:child.version,materials})}),env);
 assert.equal((await post(worker,[])).status,400);assert.equal(fires,0);assert.equal((await store.requireTask(child.id)).status,'queued');
 const materials=[{name:'evidence.txt',text:'PRIVATE_TRANSIENT_EVIDENCE'}];assert.equal((await post(createWorker({fetchFn}),materials)).status,400);assert.equal(fires,0);
 assert.equal((await post(worker,materials)).status,202);assert.equal(fires,1);assert.ok(prompt.includes('PRIVATE_TRANSIENT_EVIDENCE'));assert.equal(JSON.stringify(await store.getState()).includes('PRIVATE_TRANSIENT_EVIDENCE'),false);
 assert.equal((await post(worker,materials)).status,409);assert.equal(fires,1);
});

import {createCodexRunner,createClaudeRoutineRunner} from '../server/runners.mjs';
import {EventEmitter} from 'node:events';
import {PassThrough} from 'node:stream';
test('gated child runners accept declared transient sources without relaxing default restrictions',async()=>{
 const task={id:'source-child',prompt:'Analyze evidence',parentTaskId:'parent',assignment:sourceAssignments[0],attachments:[{id:'source',name:'evidence.txt',source:'file'}]};const materials=[{name:'evidence.txt',text:'PRIVATE_RUNNER_EVIDENCE'}];let received='';
 const config={ensureDirectory:()=>{},modelCatalog:async()=>[{model:'test-model',efforts:['high']}],spawnProcess:()=>{const c=new EventEmitter();c.stdout=new PassThrough();c.stderr=new PassThrough();c.stdin=new PassThrough();c.stdin.on('data',x=>{received+=x;});queueMicrotask(()=>{c.stdout.write(JSON.stringify({type:'item.completed',item:{type:'agent_message',text:'Verified summary'}})+'\n');c.emit('close',0);});return c;}};
 await assert.rejects(()=>createCodexRunner(config).run({task,materials}),/cannot receive/);await assert.rejects(()=>createCodexRunner({...config,sourceDelegationVersion:1}).run({task,materials,sourceDelegationVersion:0}),/cannot receive/);await createCodexRunner({...config,sourceDelegationVersion:1}).run({task,materials});assert.ok(received.includes('PRIVATE_RUNNER_EVIDENCE'));
 let body;const claudeTask={...task,assignment:sourceAssignments[1]},options={url:'https://api.anthropic.com/v1/fire',token:'test',fetchFn:async(u,o)=>{body=o.body;return Response.json({claude_code_session_id:'s',claude_code_session_url:'https://claude.ai/code/s'});}};
 await assert.rejects(()=>createClaudeRoutineRunner(options).run({task:claudeTask,materials}),/cannot receive/);await createClaudeRoutineRunner({...options,sourceDelegationVersion:1}).run({task:claudeTask,materials});assert.ok(body.includes('PRIVATE_RUNNER_EVIDENCE'));
});

for(const provider of ['codex','claude'])test(`direct ${provider} source review retains generated child evidence`,async t=>{
 const db=new TestD1();t.after(()=>db.close());const store=new D1TaskStore(db);const parent=await store.createTask({prompt:'review original evidence',attachments:[{id:'source',name:'evidence.txt',source:'file'}]});const owner=await store.claimExecution(parent.id,{provider,expectedVersion:1,sourceBound:true});const service=new Delegations(store,{sourceDelegationVersion:1}),batch=await service.allocate(parent.id,{executionId:owner.executionId,generation:owner.generation,independent:true,children:sourceAssignments});
 for(const child of batch.children){const claim=await store.claimExecution(child.id,{provider:child.assignment.provider,expectedVersion:child.version,sourceBound:true});await store.finishExecution(child.id,{...claim,content:'Generated verified result',artifacts:[{name:'summary.txt',mime:'text/plain',content:'Generated result',encoding:'utf-8'}]});}
 const review=await service.reconcile(parent.id);let firedPrompt;const env={DB:db,ACCESS_TOKEN:'test-secret-01234567890123456789',CLAUDE_ROUTINE_URL:'https://api.anthropic.com/v1/fire',CLAUDE_ROUTINE_TOKEN:'mock'};const worker=createWorker({sourceDelegationVersion:1,fetchFn:async(u,o)=>{firedPrompt=JSON.parse(o.body).text;return Response.json({claude_code_session_id:'s',claude_code_session_url:'https://claude.ai/code/s'});}});
 const route=provider==='codex'?`/api/desktop/${parent.id}/start`:`/api/tasks/${parent.id}/run`,input=provider==='codex'?{expectedVersion:review.parent.version,sourceDelegationVersion:1,sourceNames:['evidence.txt']}:{provider,expectedVersion:review.parent.version,materials:[{name:'evidence.txt',text:'PRIVATE_REVIEW_SOURCE'}]};
 const response=await worker.fetch(new Request('https://inno.test'+route,{method:'POST',headers:{authorization:'Bearer '+env.ACCESS_TOKEN,'content-type':'application/json'},body:JSON.stringify(input)}),env);assert.equal(response.status,provider==='codex'?200:202);const body=await response.json();
 if(provider==='codex'){assert.equal(body.claim.reviewInputs.length,2);assert.equal(body.claim.reviewInputs[0].artifacts[0].content,'Generated result');}else{assert.ok(firedPrompt.includes('PRIVATE_REVIEW_SOURCE'));assert.ok(firedPrompt.includes('Review manifest:'));assert.ok(firedPrompt.includes('summary.txt'));}
 assert.equal((await store.requireTask(parent.id)).delegation.state,'reviewing');assert.equal(JSON.stringify(await store.getState()).includes('PRIVATE_REVIEW_SOURCE'),false);
});

test('Codex source master preserves selected child IDs and refuses unknown references before delivery',async t=>{
 const {mkdtemp,rmdir}=await import('node:fs/promises'),{tmpdir}=await import('node:os'),path=await import('node:path');
 const directory=await mkdtemp(path.join(tmpdir(),'inno-source-plan-'));t.after(()=>rmdir(directory).catch(()=>{}));
 const task={id:'master-source',prompt:'Analyze sources',attachments:[{id:'source',name:'evidence.txt',source:'file'}]},materials=[{name:'evidence.txt',text:'PRIVATE_SOURCE_FOR_MASTER'}];let received='',children=sourceAssignments;
 const config={managedDelivery:true,sourceDelegationVersion:1,runDirectory:()=>directory,modelCatalog:async()=>[{model:'test-model',efforts:['high']}],spawnProcess:()=>{const c=new EventEmitter();c.stdout=new PassThrough();c.stderr=new PassThrough();c.stdin=new PassThrough();c.stdin.on('data',x=>{received+=x;});queueMicrotask(()=>{c.stdout.write(JSON.stringify({type:'item.completed',item:{type:'agent_message',text:JSON.stringify({summary:'Two scoped roles',artifacts:[],delegation:{independent:true,children}})}})+'\n');c.emit('close',0);});return c;}};
 const result=await createCodexRunner(config).run({task,materials});assert.deepEqual(result.delegation.children[0].sourceIds,['source']);assert.match(received,/Selectable parent source references/);assert.equal(JSON.stringify(result).includes('PRIVATE_SOURCE_FOR_MASTER'),false);
 children=sourceAssignments.map(c=>({...c,sourceIds:['unknown']}));await assert.rejects(()=>createCodexRunner(config).run({task,materials}),/Unknown delegation sourceId/);
});
for(const version of [0,1])test(`Claude source planner and state advertise source capability version ${version}`,async t=>{
 const db=new TestD1();t.after(()=>db.close());const store=new D1TaskStore(db),task=await store.createTask({prompt:'Analyze connected evidence',attachments:[{id:'source',name:'evidence.txt',source:'file'}]});let prompt='';const env={DB:db,ACCESS_TOKEN:'test-secret-01234567890123456789',CLAUDE_ROUTINE_URL:'https://api.anthropic.com/v1/fire',CLAUDE_ROUTINE_TOKEN:'mock'};const worker=createWorker({sourceDelegationVersion:version,fetchFn:async(u,o)=>{prompt=JSON.parse(o.body).text;return Response.json({claude_code_session_id:'s',claude_code_session_url:'https://claude.ai/code/s'});}});const headers={authorization:'Bearer '+env.ACCESS_TOKEN,'content-type':'application/json'};
 const state=await (await worker.fetch(new Request('https://inno.test/api/state',{headers}),env)).json();assert.equal(state.capabilities.sourceDelegationVersion,version);
 const response=await worker.fetch(new Request(`https://inno.test/api/tasks/${task.id}/run`,{method:'POST',headers,body:JSON.stringify({provider:'claude',expectedVersion:task.version,materials:[{name:'evidence.txt',text:'transient evidence'}]})}),env);assert.equal(response.status,202);assert.equal(prompt.includes('Selectable parent source references'),version===1);if(version===1)assert.match(prompt,/source-scoped work/);
});

test('source child claim requires a compatible desktop report before taking ownership',async t=>{const db=new TestD1();t.after(()=>db.close());const store=new D1TaskStore(db),batch=await sourceBatch(store),child=batch.children[0],bridge=new CloudBridge(store,{sourceDelegationVersion:1});await assert.rejects(()=>bridge.start(child.id,{expectedVersion:child.version,sourceNames:['evidence.txt']}),/compatible|updated/i);assert.equal((await store.requireTask(child.id)).status,'queued');const claim=await bridge.start(child.id,{expectedVersion:child.version,sourceNames:['evidence.txt'],sourceDelegationVersion:1});assert.equal(claim.sourceDelegationVersion,1);});
