import test from 'node:test';
import assert from 'node:assert/strict';
import {TestD1} from './helpers/d1.mjs';
import {D1TaskStore} from '../worker/store.mjs';
import {createWorker} from '../worker/index.mjs';
async function source(){const text=' PRIVATE_SELECTED_SOURCE \n',sha256=[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))].map(v=>v.toString(16).padStart(2,'0')).join('');return {text,view:{kind:'text-byte-range',start:4,end:4+text.length,sha256}};}
async function fixture(t){const DB=new TestD1();t.after(()=>DB.close());let prompt='',fires=0;const env={DB,ACCESS_TOKEN:'test-source-selection-0123456789',CLAUDE_ROUTINE_TOKEN:'test',CLAUDE_ROUTINE_URL:'https://api.anthropic.com/test/fire'};const worker=createWorker({fetchFn:async(url,input)=>{fires++;prompt=JSON.parse(input.body).text;return Response.json({claude_code_session_id:'test',claude_code_session_url:'https://claude.ai/code/test'});}});const post=async(path,input)=>{const r=await worker.fetch(new Request('https://inno.example'+path,{method:'POST',headers:{authorization:'Bearer '+env.ACCESS_TOKEN,'content-type':'application/json'},body:JSON.stringify(input)}),env);return {status:r.status,...await r.json()};};return {store:new D1TaskStore(DB),post,prompt:()=>prompt,fires:()=>fires};}
test('Claude receives selected coverage while cloud task stores metadata only',async t=>{const f=await fixture(t),{text,view}=await source();const {task}=await f.post('/api/tasks',{prompt:'Use only selected evidence',attachments:[{name:'x.txt',source:'file',size:100,view}]});const result=await f.post(`/api/tasks/${task.id}/run`,{provider:'claude',expectedVersion:1,materials:[{name:'x.txt',text,coverage:{...view,sourceSize:100,partial:true,method:'utf8_text'}}]});assert.equal(result.status,202);assert.equal(f.fires(),1);assert.match(f.prompt(),/DELIVERY AND VERIFICATION/);assert.match(f.prompt(),/not run checks/);assert.match(f.prompt(),/SOURCE COVERAGE/);assert.match(f.prompt(),/Only the selected excerpts were read/);assert.ok(f.prompt().includes(text));const stored=await f.store.requireTask(task.id);assert.equal(JSON.stringify(stored).includes('PRIVATE_SELECTED_SOURCE'),false);assert.deepEqual(stored.attachments[0].view,task.attachments[0].view);assert.equal(stored.checkpoint.sourceBound,true);});
test('changed selection fails before claim or paid-token execution',async t=>{const f=await fixture(t),{text,view}=await source();const {task}=await f.post('/api/tasks',{prompt:'Use selected evidence',attachments:[{name:'x.txt',source:'file',size:100,view}]});const result=await f.post(`/api/tasks/${task.id}/run`,{provider:'claude',expectedVersion:1,materials:[{name:'x.txt',text:text.replace('SELECTED','MODIFIED'),coverage:{...view,sourceSize:100,partial:true,method:'utf8_text'}}]});assert.equal(result.status,400);assert.equal(f.fires(),0);assert.equal((await f.store.requireTask(task.id)).status,'ready');});
