import test from 'node:test';
import assert from 'node:assert/strict';
import {createTask,sanitizeMaterials} from '../public/core/tasks.mjs';
import {exportBundle,parseBundle} from '../public/core/client.mjs';
const view={kind:'text-byte-range',start:10,end:15,sha256:'a'.repeat(64)};
test('selected source metadata survives task export without copying original text',()=>{const task=createTask({prompt:'selected evidence',attachments:[{name:'large.txt',size:100,source:'file',view:{...view,content:'PRIVATE_ORIGINAL'}}]});assert.deepEqual(task.attachments[0].view,view);const bundle=exportBundle({tasks:[task]});assert.deepEqual(parseBundle(JSON.stringify(bundle)).tasks[0].attachments[0].view,view);assert.equal(JSON.stringify(bundle).includes('PRIVATE_ORIGINAL'),false);});
test('invalid source ranges hashes and URL views are rejected',()=>{for(const invalid of [{...view,start:-1},{...view,end:1001},{...view,end:10},{...view,sha256:'invalid'},{kind:'pdf-pages',startPage:2,endPage:150,sha256:view.sha256}])assert.throws(()=>createTask({prompt:'x',attachments:[{name:'x.txt',source:'file',size:100,view:invalid}]}));assert.throws(()=>createTask({prompt:'x',attachments:[{name:'url',source:'url',url:'https://example.org',view}]}));});
test('transient material retains exact whitespace and bounded coverage only',()=>{const coverage={...view,sourceSize:100,partial:true,method:'utf8_text',secret:'PRIVATE_METADATA'};const [material]=sanitizeMaterials([{name:'x',text:' a \n',coverage}]);assert.equal(material.text,' a \n');assert.equal(material.coverage.start,10);assert.equal(JSON.stringify(material).includes('PRIVATE_METADATA'),false);});
test('total material budget uses UTF8 bytes consistently across transports',()=>{assert.throws(()=>sanitizeMaterials([{name:'a',text:'가'.repeat(150000)},{name:'b',text:'나'.repeat(100000)}]),/total material/);assert.throws(()=>sanitizeMaterials([{name:'x',text:'a',coverage:{...view,sourceSize:100,partial:false,method:'unknown'}}]));});
test('import/export removes unexpected fields nested inside a source view',()=>{const task=createTask({prompt:'x',attachments:[{name:'x.txt',size:100,source:'file',view}]});task.attachments[0].view.content='PRIVATE_NESTED_ORIGINAL';const restored=parseBundle(JSON.stringify({format:'inno-workspace-v1',tasks:[task]}));assert.deepEqual(restored.tasks[0].attachments[0].view,view);assert.equal(JSON.stringify(restored).includes('PRIVATE_NESTED_ORIGINAL'),false);});
import {verifyMaterialViews} from '../public/core/source-coverage.mjs';
test('execution rejects changed selected text or omitted saved views',async()=>{const text=' selected evidence \n';const sha256=[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))].map(v=>v.toString(16).padStart(2,'0')).join('');const view={kind:'text-byte-range',start:10,end:10+text.length,sha256};const task={attachments:[{name:'x',path:'folder/x',size:100,source:'file',view}]};const material={name:'folder/x',text,coverage:{...view,sourceSize:100,partial:true,method:'utf8_text'}};await verifyMaterialViews(task,[material]);await assert.rejects(()=>verifyMaterialViews(task,[{...material,text:text.replace('evidence','modified')}]),/changed/);await assert.rejects(()=>verifyMaterialViews(task,[]),/Reconnect/);await assert.rejects(()=>verifyMaterialViews(task,[{...material,coverage:{...material.coverage,start:11}}]),/differs/);});

test('text coverage cannot claim fewer bytes than its hashed text',async()=>{const text='twenty four bytes of text';const sha256=Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text))).toString('hex');await assert.rejects(()=>verifyMaterialViews({attachments:[]},[{name:'x',text,coverage:{kind:'text-byte-range',start:0,end:1,sourceSize:1,partial:false,method:'utf8_text',sha256}}]),/byte range differs/);});
test('PDF completeness requires consistent total page metadata',()=>{const coverage={kind:'pdf-pages',startPage:10,endPage:11,totalPages:11,sourceSize:100,sha256:'a'.repeat(64),method:'pdf_embedded_text',partial:false};assert.throws(()=>sanitizeMaterials([{name:'x',text:'x',coverage}]),/page range/);assert.throws(()=>sanitizeMaterials([{name:'x',text:'x',coverage:{...coverage,totalPages:undefined,partial:true}}]),/total pages/);const [result]=sanitizeMaterials([{name:'x',text:'x',coverage:{...coverage,partial:true}}]);assert.equal(result.coverage.totalPages,11);});

test('execution requires every ordinary connected attachment exactly once',async()=>{
 const task={attachments:[{name:'a.txt',path:'folder/a.txt',source:'file'},{name:'b.txt',source:'file'}]};
 await assert.rejects(()=>verifyMaterialViews(task,[{name:'folder/a.txt',text:'a'}]),/Reconnect/);
 await assert.rejects(()=>verifyMaterialViews(task,[{name:'folder/a.txt',text:'a'},{name:'b.txt',text:'b'},{name:'extra',text:'unassigned'}]),/Unexpected/);
 await assert.rejects(()=>verifyMaterialViews(task,[{name:'folder/a.txt',text:'a'},{name:'b.txt',text:'b'},{name:'b.txt',text:'different'}]),/Reconnect/);
 await verifyMaterialViews(task,[{name:'b.txt',text:'b'},{name:'folder/a.txt',text:'a'}]);
});
