import test from 'node:test';
import assert from 'node:assert/strict';
import {prepareTaskMaterials} from '../public/core/source-materials.mjs';
const task=()=>({id:'t',version:1,attachments:[{id:'a',name:'a.txt',path:'folder/a.txt',source:'file'}]});
const services=()=>({connected:()=>true,getFile:async()=>({}),extractText:async()=>({status:'available',text:'transient evidence'}),isCurrent:()=>true});
test('shared source preparation uses assigned names without changing saved metadata',async()=>{const t=task(),before=structuredClone(t);const materials=await prepareTaskMaterials(t,services());assert.deepEqual(materials,[{name:'folder/a.txt',text:'transient evidence'}]);assert.deepEqual(t,before);});
test('stale state during file read stops extraction and transmission',async()=>{let current=true,extractions=0;await assert.rejects(()=>prepareTaskMaterials(task(),{...services(),isCurrent:()=>current,getFile:async()=>{current=false;return {};},extractText:async()=>{extractions++;return {status:'available',text:'x'};}}),e=>e.code==='STALE_SOURCE_TASK');assert.equal(extractions,0);});
test('missing references and oversized attachment lists stop before reading originals',async()=>{let reads=0;const options={...services(),connected:()=>false,getFile:async()=>{reads++;return {};}};await assert.rejects(()=>prepareTaskMaterials(task(),options),/연결/);const many={attachments:Array.from({length:21},(_,i)=>({id:String(i),name:String(i),source:'file'}))};await assert.rejects(()=>prepareTaskMaterials(many,{...options,connected:()=>true}),/20/);assert.equal(reads,0);});
test('source preparation rejects truncation and counts multibyte text against the total budget',async()=>{await assert.rejects(()=>prepareTaskMaterials(task(),{...services(),extractText:async()=>({status:'truncated',text:'cut'})}),/조회 범위/);const t={attachments:[{id:'a',name:'a',source:'file'},{id:'b',name:'b',source:'file'}]};await assert.rejects(()=>prepareTaskMaterials(t,{...services(),extractText:async()=>({status:'available',text:'가'.repeat(110000)})}),/범위|material/);});

import {extractSourceView,verifySourceView} from '../public/core/source-views.mjs';
test('shared preparation reads the exact saved text window and rejects changed content',async()=>{const original=new File(['prefix selected suffix'],'a.txt',{type:'text/plain',lastModified:1});const selected=await extractSourceView(original,{kind:'text-byte-range',start:7,end:15});const t=task();t.attachments[0].size=original.size;t.attachments[0].view=selected.view;const options={...services(),getFile:async()=>original,verifyView:verifySourceView,extractText:async()=>{throw Error('must use selected view');}};const result=await prepareTaskMaterials(t,options);assert.equal(result[0].text,'selected');assert.equal(result[0].coverage.start,7);assert.equal(result[0].coverage.end,15);const changed=new File(['prefix SELECTED suffix'],'a.txt',{type:'text/plain',lastModified:1});await assert.rejects(()=>prepareTaskMaterials(t,{...options,getFile:async()=>changed}),/changed/);});
test('state changing during extraction prevents returning stale material',async()=>{let valid=true;await assert.rejects(()=>prepareTaskMaterials(task(),{...services(),isCurrent:()=>valid,extractText:async()=>{valid=false;return {status:'available',text:'outdated'};}}),e=>e.code==='STALE_SOURCE_TASK');});
test('an oversized whole-file format asks for a smaller file instead of a range it cannot select',async()=>{const t={attachments:[{id:'x',name:'data.xlsx',source:'file'}]};await assert.rejects(()=>prepareTaskMaterials(t,{...services(),extractText:async()=>({status:'truncated',text:'cut'})}),e=>/나눠/.test(e.message)&&!/조회 범위를 선택/.test(e.message));await assert.rejects(()=>prepareTaskMaterials(task(),{...services(),extractText:async()=>({status:'truncated',text:'cut'})}),/조회 범위를 선택.*UTF-8/);});
